area = input().split()
A = float(area[0])
B = float(area[1])
C = float(area[2])
print(f"TRIANGULO: {(A*C)/2:.3f}")
print(f"CIRCULO: {3.14159*(C**2):.3f}")
print(f"TRAPEZIO: {(A+B)*C/2:.3f}")
print(f"QUADRADO: {B**2:.3f}")
print(f"RETANGULO: {A*B:.3f}")